server:
  port: 8089
  
spring:
  mvc:
    view:
      prefix: /pages/
      suffix: .html
      
  datasource:
    url: jdbc:mysql://localhost:3306/yangxitest?useUnicode=true&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.yx.entity
  mapper-locations: classpath*:com/yx/mapper/*.xml

logging:
  level:
    com.yx.dao: debug